name: oro_drip_irrigation
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  linked_scroll_controller: ^0.2.0
  responsive_grid_list: ^1.4.0
  flutter_svg: ^2.0.16
  intl: ^0.20.2
  syncfusion_flutter_charts: ^28.2.4+1
  sleek_circular_slider: ^2.0.1
  material_design_icons_flutter: ^7.0.7296
  mqtt_client: ^10.5.1
  uuid: ^4.5.1
  intl_phone_number_input: ^0.7.4
  data_table_2: ^2.5.18
  table_calendar: ^3.2.0
  loading_indicator: ^3.1.1
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  flutter_portal: ^1.1.4
  chat_bubbles: ^1.5.0
  timezone: ^0.10.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_flavorizr: ^2.2.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/Images/
     - assets/Images/Svg/
     - assets/Images/Fertilization/
     - assets/Images/Filtration/
     - assets/Images/Png/
     - assets/Images/Png/Oro/
     - assets/Images/Png/SmartComm/
     - assets/Images/Source/
     - assets/png_images/
     - assets/svg_images/
     - assets/SVGPicture/
     - assets/png_images/
     - assets/Images/Source/
     - assets/mob_dashboard/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: ZuumeRough
#      fonts:
#        - asset: assets/fonts/fontspring-demo-zuumerough-bold.otf
#          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flavorizr:
  flavors:
    oroDevelopment:
      app:
        name: "ORO"
      android:
        applicationId: "com.example.oroDevelopment"
#      ios:
#        bundleId: "com.example.apple"
    oroProduction:
      app:
        name: "ORO"
      android:
        applicationId: "com.example.oroProduction"
    #      ios:
    #        bundleId: "com.example.apple"
    smartComm:
      app:
        name: "SMART COMM"
      android:
        applicationId: "com.example.SmartComm"
#      ios:
#        bundleId: "com.example.banana"
#      macos:
#        bundleId: "com.example.banana"
